name=Sequent Microsystems MegaInd
version=1.0.0
author=Sequent Microsystems
maintainer=Sequent Microsystems <support@sequentmicrosystems.com>
sentence=Industrial Automation 8-Layer Stackable HAT for Raspberry Pi
paragraph=his library provide the software tools for use with the Industrial Automation 8-Layer Stackable HAT for Raspberry Pi with any Arduino card that have a I2C port
category=Signal Control
url=https://sequentmicrosystems.com/products/industrial-automation-for-raspberry-pi
architectures=*
depends=